---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when:
    - not is_container|bool

- name: Restart openwebui
  ansible.builtin.service:
    name: open-webui
    state: restarted
  when:
    - not is_container|bool

- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  when:
    - not is_container|bool
